/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jual_motor;

/**
 *
 * @author HP
 */
public class jual_motorFrame extends javax.swing.JFrame {

    /**
     * Creates new form jual_motorFrame
     */
    public jual_motorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kodeMotor = new javax.swing.JLabel();
        cbkodeMotor = new javax.swing.JComboBox<>();
        namaMotor = new javax.swing.JLabel();
        txtnamaMotor = new javax.swing.JTextField();
        hargaMotor = new javax.swing.JLabel();
        txthargaMotor = new javax.swing.JTextField();
        diskoN = new javax.swing.JLabel();
        totBayar = new javax.swing.JLabel();
        btndiskoN = new javax.swing.JButton();
        btntotaL = new javax.swing.JButton();
        btnuangBayar = new javax.swing.JButton();
        uangKembalian = new javax.swing.JLabel();
        txtuangKembalian = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtuangBayar = new javax.swing.JTextField();
        txtdiskoN = new javax.swing.JTextField();
        txtuniT = new javax.swing.JTextField();
        txttotBayar = new javax.swing.JTextField();
        uniT = new javax.swing.JLabel();
        uangBayar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kodeMotor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kodeMotor.setText("Kode Motor        : ");

        cbkodeMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A01\t", "A02", "A03", "A04", "A05" }));
        cbkodeMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkodeMotorActionPerformed(evt);
            }
        });

        namaMotor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaMotor.setText("Nama Motor       : ");

        txtnamaMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaMotorActionPerformed(evt);
            }
        });

        hargaMotor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hargaMotor.setText("Harga Motor       :");

        txthargaMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaMotorActionPerformed(evt);
            }
        });

        diskoN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        diskoN.setText("Diskon                :");

        totBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totBayar.setText("Total Bayar         :");

        btndiskoN.setText("DISKON!!!");
        btndiskoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiskoNActionPerformed(evt);
            }
        });

        btntotaL.setText("TOTAL");
        btntotaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotaLActionPerformed(evt);
            }
        });

        btnuangBayar.setText("BAYAR");
        btnuangBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuangBayarActionPerformed(evt);
            }
        });

        uangKembalian.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uangKembalian.setText("Uang Kembalian :");

        txtuangKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuangKembalianActionPerformed(evt);
            }
        });

        jButton2.setText("KEMBALI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtuangBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuangBayarActionPerformed(evt);
            }
        });

        txtdiskoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiskoNActionPerformed(evt);
            }
        });

        txtuniT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuniTActionPerformed(evt);
            }
        });

        txttotBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotBayarActionPerformed(evt);
            }
        });

        uniT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uniT.setText("Unit                    :");

        uangBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uangBayar.setText("Uang Bayar         :");

        jPanel2.setBackground(new java.awt.Color(255, 0, 255));

        jLabel2.setBackground(new java.awt.Color(255, 102, 255));
        jLabel2.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel2.setText("FORM BELI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namaMotor)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtnamaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kodeMotor)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbkodeMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(uangBayar)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtdiskoN, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btndiskoN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(169, 169, 169))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diskoN, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttotBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hargaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txthargaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(jButton2)
                                    .addGap(45, 45, 45)
                                    .addComponent(jButton3)
                                    .addGap(111, 111, 111)
                                    .addComponent(uangKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(uniT)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtuniT, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtuangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnuangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btntotaL, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(477, 477, 477))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtuangKembalian)
                                .addContainerGap())))))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeMotor)
                    .addComponent(cbkodeMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnamaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaMotor))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthargaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaMotor))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuniT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uniT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdiskoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uangBayar)
                    .addComponent(btndiskoN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diskoN)
                    .addComponent(btntotaL))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtuangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totBayar)
                    .addComponent(btnuangBayar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(uangKembalian)
                    .addComponent(txtuangKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbkodeMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkodeMotorActionPerformed
        // TODO add your handling code here:
        String kodeMotor,namaMotor;
        int hargaMotor;

        kodeMotor = String.valueOf(cbkodeMotor.getSelectedItem());

        if (kodeMotor.equals("A01")){
            namaMotor="Honda Vario 150";
            hargaMotor=24000000;
        }else
            if (kodeMotor.equals("A02")){
            namaMotor="Yamaha Aerox 155";
            hargaMotor=28000000;
        }else
                 if (kodeMotor.equals("A03")){
                namaMotor="Suzuki GSX-R 150";
                hargaMotor=29000000;
        }else
                    if (kodeMotor.equals("A04")){
                    namaMotor="Kawasaki Ninja 250 SE";
                    hargaMotor=66000000;
        }else
        {               
                        namaMotor="Honda CBR 250RR SP";
                        hargaMotor=77000000;
        }
        txtnamaMotor.setText(""+namaMotor);
        txthargaMotor.setText(""+hargaMotor);
        

    }//GEN-LAST:event_cbkodeMotorActionPerformed

    private void txtnamaMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaMotorActionPerformed

    private void txthargaMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaMotorActionPerformed

    private void btndiskoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiskoNActionPerformed
        // TODO add your handling code here:
        int hargaMotor, diskoN;
        int uniT;

        uniT = Integer.parseInt(txtuniT.getText());
        hargaMotor = Integer.parseInt(txthargaMotor.getText());

        if(uniT > 1) {
            diskoN = (int) (hargaMotor * 0.20);
        }else
        {
            diskoN = 0;
        }
        txtdiskoN.setText(""+diskoN);

    }//GEN-LAST:event_btndiskoNActionPerformed

    private void btntotaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotaLActionPerformed
        // TODO add your handling code here:
        int hargaMotor,diskoN,totBayar;
        int uniT;

        hargaMotor = Integer.parseInt(txthargaMotor.getText());
        uniT = Integer.parseInt(txtuniT.getText());
        diskoN = Integer.parseInt(txtdiskoN.getText());

        totBayar = (hargaMotor * uniT)-diskoN;
        txttotBayar.setText(""+totBayar);
    }//GEN-LAST:event_btntotaLActionPerformed

    private void btnuangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuangBayarActionPerformed
        // TODO add your handling code here:
        int totBayar, uangBayar,uangKembalian;
        
        totBayar = Integer.parseInt(txttotBayar.getText());
        uangBayar = Integer.parseInt(txtuangBayar.getText());
        
        if (uangBayar > totBayar){
            uangKembalian = uangBayar - totBayar;
            txtuangKembalian.setText(""+uangKembalian);
        }else
        { txtuangKembalian.setText("Yah duid nya kurang :( " );
        
        }

    }//GEN-LAST:event_btnuangBayarActionPerformed

    private void txtuangKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuangKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuangKembalianActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        login_frame n = new login_frame();
        n.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtnamaMotor.setText("");
        txthargaMotor.setText("");
        txtuniT.setText("");
        txtdiskoN.setText("");
        txttotBayar.setText("");
        txtuangBayar.setText("");
        txtuangKembalian.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtuangBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuangBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuangBayarActionPerformed

    private void txtdiskoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiskoNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiskoNActionPerformed

    private void txtuniTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuniTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuniTActionPerformed

    private void txttotBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jual_motorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jual_motorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jual_motorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jual_motorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jual_motorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndiskoN;
    private javax.swing.JButton btntotaL;
    private javax.swing.JButton btnuangBayar;
    private javax.swing.JComboBox<String> cbkodeMotor;
    private javax.swing.JLabel diskoN;
    private javax.swing.JLabel hargaMotor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel kodeMotor;
    private javax.swing.JLabel namaMotor;
    private javax.swing.JLabel totBayar;
    private javax.swing.JTextField txtdiskoN;
    private javax.swing.JTextField txthargaMotor;
    private javax.swing.JTextField txtnamaMotor;
    private javax.swing.JTextField txttotBayar;
    private javax.swing.JTextField txtuangBayar;
    private javax.swing.JTextField txtuangKembalian;
    private javax.swing.JTextField txtuniT;
    private javax.swing.JLabel uangBayar;
    private javax.swing.JLabel uangKembalian;
    private javax.swing.JLabel uniT;
    // End of variables declaration//GEN-END:variables
}
